config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
   resources :posts do
    collection do
      post :confirm
    end
    member do
      patch :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    validates :image, presence: true
    validates :content, presence: true, length: { in: 1..200 }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    validates :name,  presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
                      before_validation { email.downcase! }
                      has_secure_password
                      validates :password, presence: true, length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception
    include SessionsHelper
    private
    def login_required
      redirect_to new_session_path unless current_user
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show ,:edit, :update, :destroy ]

  def index
    @posts = Post.all.order(created_at: "DESC")
  end

  def new
    @post = Post.new
  end
  
  def show
    @post = set_post
  end

  def edit
  end

  def destroy
    @post.destroy
      redirect_to posts_path, notice:"投稿を削除しました！"
  end

  def create
    @post = current_user.posts.build(post_params)
    if params[:back]
      render :new
    else
      if @post.save
        redirect_to posts_path
      else
        render :new
      end
    end
  end

  def update
    if params[:back]
      render :edit
    elsif @post.update(post_params)
      redirect_to posts_path, notice: "編集しました！"
    else
      render :edit
    end
  end

  def confirm
    @post = current_user.posts.build(post_params)
    @post.user_id = current_user.id
    render :new if @post.invalid?
  end

  private

  def post_params
    params.require(:post).permit(:id, :content, :image ,:image_cache)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to posts_path

    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to user_path(@user.id)
    else
      render :new if @user.invalid?
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_posts_path

    elsif action_name == 'edit' || action_name == 'update'
      confirm_post_path(@post.id)
    end
  end

  def confirm_new_or_edit
    unless @post.id?
      posts_path
    else
      post_path(@post)
    end
 end

 def confirm_form_method
  @post.id ? 'patch' : 'post'
end

end

app/helpers/sessions_helper.rb
module SessionsHelper
   
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        current_user.present?
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <header>
        <ul class="top_menu row">
          <% if logged_in? %>
            <li class="col-md-2"><%= "FamilyBook" %></li>
            <li class="col-md-8"></li>
            <li class="col-md-2"><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
          <% else %>
            <li class="col-md-2"><%= "FamilyBook" %></li>
            <li class="col-md-8"></li>
            <li class="col-md-2"><%= link_to "Home" %></li>
           <% end %>
        </ul>
    </header>
    <body>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>

      <%= yield %>
    </body>
</html>

app/views/posts/confirm.html.erb
<h3>この内容で投稿します。</h3>
<%= form_with(model: @post, url: choose_new_or_edit, method: confirm_new_or_edit, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image %>
    <p>投稿:<%= @post.content %></p>
      <%= form.hidden_field @post.image %>
      <%= form.hidden_field :image_cache %>
      <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
  <p><%= form.submit  "登録する" %></p>
  <p><%= form.submit "戻る", name: "back"%></p>
<% end %>


app/views/posts/edit.html.erb
<body>
  <h3>投稿を更新する</h3>
  <%= form_with(model: @post, url: confirm_new_or_edit, local: true) do |form| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
          <h2><%= @post.errors.count %>件のエラーがあります。</h2>
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
          <p><%= form.label :content %></p>
          <p><%= form.text_area  :content , size: "40-20" %></p>
          <p><%= form.label :image %></p>
          <p><%= form.file_field :image %></p>
          <p><%= form.hidden_field :image_cache %></p>
      <p><%= form.submit "更新する" %><p>
  <% end %>
  <p><button><%= link_to "戻る", posts_path %></button><p>
</body>

app/views/posts/index.html.erb
<% provide(:title, 'index') %>
<h3>今日はどんな日だった？ <%= current_user.name %> さん</h3>
<button><%= link_to "その出来事を投稿しよう", new_post_path %></button><br>
<body>
  <% if @posts.count > 0 %>
    <% @posts.each do |post| %>
      <table>
        <tr>
            <td><%= post.user.name %></td>
        </tr>
        <tr>
            <td><%= post.created_at.strftime("%Y年 %m月 %d日 %H時 %M分") %></td>
        </tr>
        <tr>
            <td><button><%= link_to '詳細', post_path(post.id) %></button>
              <% if current_user.id == post.user_id %>
                <button><%= link_to '編集', edit_post_path(post.id) %></button>
                <button><%= link_to '削除', post_path(post.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></button>
              <% end %>
            </td>
        </tr>
        <tr>
            <td><%= post.content %></td>
        </tr>
        <tr>
            <td><%= image_tag(post.image.url) if post.image && post.image.url %></td>
        </tr>
      </table>
    <% end %>
  <% end %>
</body>

app/views/posts/new.html.erb
<body>
  <h3>投稿しよう</h3>
  <%= form_with(model: @post, url: confirm_posts_path, local: true) do |form| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
          <h2><%= @post.errors.count %>件のエラーがあります。</h2>
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
          <p><%= form.label :content %></p>
          <p><%= form.text_area :content ,  size: "40-20" %></p>
          <p><%= form.label :image %><p>
          <p><%= form.file_field :image %></p>
          <p><%= form.hidden_field :image_cache %></p>
      <p><%= form.submit "投稿する" %><p>
  <% end %>
  <button><%= link_to "一覧画面にもどる", posts_path %></button>
</body>

app/views/posts/show.html.erb
<h3>詳細画面</h3>
  投稿<br>
  <%= @post.content %><br>
  写真<br>
  <%= image_tag(@post.image.url) if @post.image && @post.image.url %><br>
  <button><%= link_to "戻る", posts_path %></button>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>
<h1>新規登録</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
<p><%= f.label :name %></p>
<p><%= f.text_field :name %></p>
<p><%= f.label :email %></p>
<p><%= f.email_field :email %></p>
<p><%= f.label :password %></p>
<p><%= f.password_field :password %></p>
<p><%= f.label :password_confirmation %></p>
<p><%= f.password_field :password_confirmation %></p>
<p><%= f.submit "アカウントの作成する" %></p>
<% end %>
<button><%= link_to "ログイン画面に戻る", new_session_path %></button>


app/views/users/show.html.erb
<h5>アカウントが登録されました</h5>
<p><h4><%= @user.name %></h4></p>
<p><h5>メールアドレス</h5></p>
<p><h4><%= @user.email %><h4></p>
<p><h5>ログイン画面へ戻る</h5></p>
<button><%= link_to "ログイン", new_session_path %></button>